//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App2Night.Model.Language {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App2Night.Model.Language.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this App.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms and conditions..
        /// </summary>
        public static string AcceptAgb {
            get {
                return ResourceManager.GetString("AcceptAgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting party.
        /// </summary>
        public static string AcceptingParty {
            get {
                return ResourceManager.GetString("AcceptingParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm all general terms and condition&apos;s..
        /// </summary>
        public static string AgbAcception {
            get {
                return ResourceManager.GetString("AgbAcception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read AGB.
        /// </summary>
        public static string AgbContent {
            get {
                return ResourceManager.GetString("AgbContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGB of this App.
        /// </summary>
        public static string AgbHeader {
            get {
                return ResourceManager.GetString("AgbHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Cityname {
            get {
                return ResourceManager.GetString("Cityname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Settings.
        /// </summary>
        public static string ClearCacheSettingsHeader {
            get {
                return ResourceManager.GetString("ClearCacheSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will delete local caches on device. Your aren&apos;t able anymore to load cached parties..
        /// </summary>
        public static string ClearCacheUsage {
            get {
                return ResourceManager.GetString("ClearCacheUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear all cache?..
        /// </summary>
        public static string ClearCacheValid {
            get {
                return ResourceManager.GetString("ClearCacheValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the commitment state failed.
        /// </summary>
        public static string CommitmentChangeFailed {
            get {
                return ResourceManager.GetString("CommitmentChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment state changed to {0}.
        /// </summary>
        public static string CommitmentStateChangedTo {
            get {
                return ResourceManager.GetString("CommitmentStateChangedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t attend to a party yet! Former parties will be visible here..
        /// </summary>
        public static string ContHistory {
            get {
                return ResourceManager.GetString("ContHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no parties that fit your interests. Try to modify your search filters..
        /// </summary>
        public static string ContIntParty {
            get {
                return ResourceManager.GetString("ContIntParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue anonym.
        /// </summary>
        public static string ContinueAnonymous {
            get {
                return ResourceManager.GetString("ContinueAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t enter a party yet. Tab to start searching..
        /// </summary>
        public static string ContMyParty {
            get {
                return ResourceManager.GetString("ContMyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a party.
        /// </summary>
        public static string CreateAParty {
            get {
                return ResourceManager.GetString("CreateAParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Party.
        /// </summary>
        public static string CreateParty {
            get {
                return ResourceManager.GetString("CreateParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM/dd/yyyy}.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string DateString {
            get {
                return ResourceManager.GetString("DateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Adress.
        /// </summary>
        public static string EmailAdress {
            get {
                return ResourceManager.GetString("EmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GPS.
        /// </summary>
        public static string EnableGps {
            get {
                return ResourceManager.GetString("EnableGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is made with Xamarin.Forms connected to a Microsoft Azure Web API made with Asp.Net. You can find the sourcecode for this project at Github..
        /// </summary>
        public static string GeneralContent {
            get {
                return ResourceManager.GetString("GeneralContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using App2Night. This App is the product of a university project by Stefan Machmeier and Konrad Müller at the Baden-Wuerttemberg Cooperative State University Stuttgart - campus Horb..
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS settings.
        /// </summary>
        public static string GpsSettingHeader {
            get {
                return ResourceManager.GetString("GpsSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need your position to locate parties near you. You can always disable GPS for this App and set a position manualy..
        /// </summary>
        public static string GpsUsage {
            get {
                return ResourceManager.GetString("GpsUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not participate a party yet..
        /// </summary>
        public static string HistoryNoContent {
            get {
                return ResourceManager.GetString("HistoryNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr..
        /// </summary>
        public static string HNumber {
            get {
                return ResourceManager.GetString("HNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parties near you.
        /// </summary>
        public static string IntParty {
            get {
                return ResourceManager.GetString("IntParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand..
        /// </summary>
        public static string IUnderstand {
            get {
                return ResourceManager.GetString("IUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were not able to load all party data, retry?.
        /// </summary>
        public static string LoadDataFailed {
            get {
                return ResourceManager.GetString("LoadDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading parties failed..
        /// </summary>
        public static string LoadFailedShort {
            get {
                return ResourceManager.GetString("LoadFailedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is not enabled for this app or available on your device.\n Activate the location for this device and restart the app to see a beautiful map here..
        /// </summary>
        public static string LocationNotEnabled {
            get {
                return ResourceManager.GetString("LocationNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need the permission to acccess your location to find parties near you..
        /// </summary>
        public static string LocationPermissions {
            get {
                return ResourceManager.GetString("LocationPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login now!.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google maps is not installed on this device..
        /// </summary>
        public static string MapsNotInstalled {
            get {
                return ResourceManager.GetString("MapsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My parties.
        /// </summary>
        public static string MyParties {
            get {
                return ResourceManager.GetString("MyParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyEvents.
        /// </summary>
        public static string MyParty {
            get {
                return ResourceManager.GetString("MyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not note, accept or create a party yet..
        /// </summary>
        public static string NoNotedPartiesContent {
            get {
                return ResourceManager.GetString("NoNotedPartiesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note party.
        /// </summary>
        public static string NotingParty {
            get {
                return ResourceManager.GetString("NotingParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device is not connected to the internet..
        /// </summary>
        public static string OfflineContent {
            get {
                return ResourceManager.GetString("OfflineContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to party.
        /// </summary>
        public static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent parties.
        /// </summary>
        public static string PartyHistory {
            get {
                return ResourceManager.GetString("PartyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party name.
        /// </summary>
        public static string PartyName {
            get {
                return ResourceManager.GetString("PartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission needed.
        /// </summary>
        public static string PermissionNeeded {
            get {
                return ResourceManager.GetString("PermissionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a party.
        /// </summary>
        public static string PickAParty {
            get {
                return ResourceManager.GetString("PickAParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a Party.
        /// </summary>
        public static string PickParty {
            get {
                return ResourceManager.GetString("PickParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate!.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejecting party.
        /// </summary>
        public static string RejectingParty {
            get {
                return ResourceManager.GetString("RejectingParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload data.
        /// </summary>
        public static string ReloadData {
            get {
                return ResourceManager.GetString("ReloadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last request got lost and we can&apos;t find it anymore :( Dont feel betrayed, we will handle your future requests even more carefull and give him more time! To help us handling your request, please make sure you are actually connected to the internet..
        /// </summary>
        public static string RequestFailExplenation {
            get {
                return ResourceManager.GetString("RequestFailExplenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for parties failed..
        /// </summary>
        public static string SearchingPartiesFailed {
            get {
                return ResourceManager.GetString("SearchingPartiesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to access your local storage to create a persistant user experience, the files wont be greater then 5mb and encrypted..
        /// </summary>
        public static string StoragePermissions {
            get {
                return ResourceManager.GetString("StoragePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We successfully synchronised you parties..
        /// </summary>
        public static string SyncSuccess {
            get {
                return ResourceManager.GetString("SyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party librarys.
        /// </summary>
        public static string ThirdPartyTitle {
            get {
                return ResourceManager.GetString("ThirdPartyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:hh:mm tt}.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Other View.
        /// </summary>
        public static string ToOtherView {
            get {
                return ResourceManager.GetString("ToOtherView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created!.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User creation failed..
        /// </summary>
        public static string UserCreationFailed {
            get {
                return ResourceManager.GetString("UserCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in..
        /// </summary>
        public static string UserLoggedIn {
            get {
                return ResourceManager.GetString("UserLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found {0} parties near you..
        /// </summary>
        public static string WeFoundPartiesNearYou {
            get {
                return ResourceManager.GetString("WeFoundPartiesNearYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to App2Night {0}! We send you an e-mail with a confirmation link. You can create parties after confirming your account..
        /// </summary>
        public static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        public static string Zipcode {
            get {
                return ResourceManager.GetString("Zipcode", resourceCulture);
            }
        }
    }
}
