// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace App2Night.Data.Language {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App2Night.Data.Language.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string AcceptAgb {
            get {
                return ResourceManager.GetString("AcceptAgb", resourceCulture);
            }
        }
        
        public static string ContinueAnonymous {
            get {
                return ResourceManager.GetString("ContinueAnonymous", resourceCulture);
            }
        }
        
        public static string CreateAParty {
            get {
                return ResourceManager.GetString("CreateAParty", resourceCulture);
            }
        }
        
        public static string EmailAdress {
            get {
                return ResourceManager.GetString("EmailAdress", resourceCulture);
            }
        }
        
        public static string PartyHistory {
            get {
                return ResourceManager.GetString("PartyHistory", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string PickAParty {
            get {
                return ResourceManager.GetString("PickAParty", resourceCulture);
            }
        }
        
        public static string GpsSettingHeader {
            get {
                return ResourceManager.GetString("GpsSettingHeader", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        public static string PartyName {
            get {
                return ResourceManager.GetString("PartyName", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        public static string HNumber {
            get {
                return ResourceManager.GetString("HNumber", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string Zipcode {
            get {
                return ResourceManager.GetString("Zipcode", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        public static string CreateParty {
            get {
                return ResourceManager.GetString("CreateParty", resourceCulture);
            }
        }
        
        public static string PickParty {
            get {
                return ResourceManager.GetString("PickParty", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        public static string IntParty {
            get {
                return ResourceManager.GetString("IntParty", resourceCulture);
            }
        }
        
        public static string ContIntParty {
            get {
                return ResourceManager.GetString("ContIntParty", resourceCulture);
            }
        }
        
        public static string MyParty {
            get {
                return ResourceManager.GetString("MyParty", resourceCulture);
            }
        }
        
        public static string ContMyParty {
            get {
                return ResourceManager.GetString("ContMyParty", resourceCulture);
            }
        }
        
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        public static string ContHistory {
            get {
                return ResourceManager.GetString("ContHistory", resourceCulture);
            }
        }
        
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        public static string EnableGps {
            get {
                return ResourceManager.GetString("EnableGps", resourceCulture);
            }
        }
        
        public static string GpsUsage {
            get {
                return ResourceManager.GetString("GpsUsage", resourceCulture);
            }
        }
        
        public static string Cityname {
            get {
                return ResourceManager.GetString("Cityname", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        public static string ClearCacheSettingsHeader {
            get {
                return ResourceManager.GetString("ClearCacheSettingsHeader", resourceCulture);
            }
        }
        
        public static string ClearCacheUsage {
            get {
                return ResourceManager.GetString("ClearCacheUsage", resourceCulture);
            }
        }
        
        public static string ClearCacheValid {
            get {
                return ResourceManager.GetString("ClearCacheValid", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string AgbContent {
            get {
                return ResourceManager.GetString("AgbContent", resourceCulture);
            }
        }
        
        public static string AgbHeader {
            get {
                return ResourceManager.GetString("AgbHeader", resourceCulture);
            }
        }
        
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        public static string HistoryNoContent {
            get {
                return ResourceManager.GetString("HistoryNoContent", resourceCulture);
            }
        }
        
        public static string AgbAcception {
            get {
                return ResourceManager.GetString("AgbAcception", resourceCulture);
            }
        }
        
        public static string OfflineContent {
            get {
                return ResourceManager.GetString("OfflineContent", resourceCulture);
            }
        }
        
        public static string NoNotedPartiesContent {
            get {
                return ResourceManager.GetString("NoNotedPartiesContent", resourceCulture);
            }
        }
        
        public static string ToOtherView {
            get {
                return ResourceManager.GetString("ToOtherView", resourceCulture);
            }
        }
        
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        public static string GeneralContent {
            get {
                return ResourceManager.GetString("GeneralContent", resourceCulture);
            }
        }
        
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        public static string ThirdPartyTitle {
            get {
                return ResourceManager.GetString("ThirdPartyTitle", resourceCulture);
            }
        }
    }
}
